// src/components/Navbar.svelte
<script lang="ts">
  import { supabase } from "../lib/supabaseClient"
</script>

<nav class="navbar sticky top-0 z-10 px-4 bg-base-300">
  <div class="navbar-start">
    <p class="normal-case text-xl">Nabu</p>
  </div>
  <div class="flex-none navbar-end">
    <div class="dropdown dropdown-end">
      <div tabindex="-1" class="btn btn-ghost btn-circle avatar">
        <ion-icon name="person-circle-outline" class="w-8 h-8" />
      </div>
      <ul
        tabindex="-1"
        class="menu menu-compact dropdown-content mt-2 p-2 bg-base-100 rounded-md w-48 shadow-xl"
      >
        <li>
          <button
            type="button"
            class="button block"
            on:click={() => supabase.auth.signOut()}
          >
            Sign Out
          </button>
        </li>
      </ul>
    </div>
  </div>
</nav>

// src/app/components/navbar/navbar.component.ts
import { Component } from '@angular/core'
import { Router } from '@angular/router'
import { SupabaseService } from 'src/app/services/supabase.service'

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html'
})
export class NavbarComponent {
  constructor(
    private readonly supabase: SupabaseService,
    private router: Router
  ) {}

  async signOut(): Promise<void> {
    await this.supabase.signOut()
    this.router.navigate(['/'], { replaceUrl: true })
  }
}

<nav class="navbar px-4">
  <div class="navbar-start">
    <p class="font-medium text-xl">Nabu</p>
  </div>
  <div class="flex-none navbar-end">
    <div class="dropdown dropdown-end">
      <div tabindex="0" class="btn btn-ghost btn-square avatar">
        <ion-icon name="person-circle-outline" class="w-8 h-8" />
      </div>
      <ul tabindex="-1" class="menu dropdown-content mt-2 p-2 bg-base-100 rounded-md w-48 shadow">
        <li>
          <button type="button" (click)='signOut()'>
            Sign Out
          </button>
        </li>
      </ul>
    </div>
  </div>
</nav>
