// src/app/components/todo/todo.component.ts
import { Component, Input, OnInit } from '@angular/core'
import { SupabaseService } from 'src/app/services/supabase.service'
import { TodoInterface } from 'src/app/types/TodoInterface'

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html'
})
export class TodoComponent implements OnInit {
  @Input({ required: true }) todo!: TodoInterface

  isCompleted!: boolean

  constructor(private readonly supabase: SupabaseService) {}

  ngOnInit(): void {
    this.isCompleted = this.todo.is_complete
  }

  async toggleCompleted(): Promise<void> {
    try {
      const { data, error } = await this.supabase.toggleTodo(
        this.todo.id,
        this.isCompleted
      )
      if (error) throw error
      this.isCompleted = data.is_complete
    } catch (error) {
      if (error instanceof Error) {
        console.log('error', error)
      }
    }
  }
}

<li class="join join-horizontal w-full grid grid-cols-[1fr_0fr] items-center border border-base-300 shadow">

  <div class="join-item p-3 grid grid-cols-[0.9fr_0.1fr] sm:grid-cols-[0.7fr_0.3fr] justify-between items-center gap-2">
    <p class="truncate flex-shrink">{{todo.task}}</p>

    <div class="flex flex-row justify-between items-center text-sm gap-2">
      <p class="font-light">Est.(h): <span class="font-medium">{{todo.estimated_time}}</span></p>
      <p class="font-light">Value: <span class="font-medium">{{todo.task_value}}</span></p>
    </div>
  </div>

  <button class="join-item p-4 btn rounded h-full">
    <ion-icon name="create-outline" class="w-4 h-4"></ion-icon>
  </button>
</li>

// src/components/Todo.svelte
<script lang="ts">
  import { supabase } from "../lib/supabaseClient"

  export let todo: {
    task: string
    id: number
    is_complete: boolean
    task_value: number
    estimated_time: number
  }
  export let onDelete = () => {}

  let isCompleted = todo.is_complete

  const toggle = async () => {
    try {
      const { data, error } = await supabase
        .from("todos")
        .update({ is_complete: !isCompleted })
        .eq("id", todo.id)
        .select("is_complete")
        .single()
      if (error) {
        throw error
      }
      isCompleted = data.is_complete
    } catch (error) {
      console.log("error", error)
    }
  }
</script>

<li class="collapse collapse-arrow join-item border border-base-300">
  <input type="radio" name="accordionTask" />
  <div
    class="collapse-title text-sm font-medium grid grid-cols-[0.65fr_0.35fr] justify-between items-center gap-4"
  >
    <p class="truncate flex-shrink">{todo.task}</p>
    <div class="flex flex-row justify-between gap-4">
      <p>Est.(h): {todo.estimated_time}</p>
      <p>Value: {todo.task_value}</p>
    </div>
  </div>
  <div class="collapse-content flex justify-between items-center gap-4">
    <p>{todo.task}</p>
    <div>
      <input
        class="cursor-pointer"
        type="checkbox"
        on:change={toggle}
        bind:checked={isCompleted}
      />
    </div>
    <button on:click={onDelete}>
      <ion-icon
        name="close-outline"
        class="w-4 h-4 border-2 hover:border-black rounded"
      />
    </button>
  </div>
</li>
