// src/App.tsx
import { Redirect, Route } from "react-router-dom";
import { IonApp, IonRouterOutlet, setupIonicReact } from "@ionic/react";
import { IonReactRouter } from "@ionic/react-router";

import "@ionic/react/css/ionic.bundle.css";

/* Theme variables */
import "./theme/variables.css";
import Login from "./pages/Login";
import Account from "./pages/Account";
import { useEffect, useState } from "react";
import { Session } from "@supabase/supabase-js";
import { supabase } from "./lib/SupabaseConfig";

setupIonicReact();

export default function App() {
  const [session, setSession] = useState<Session | null>(null);

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session);
    });

    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session);
    });
  }, []);

  return (
    <IonApp>
      <IonReactRouter>
        <IonRouterOutlet>
          <Route exact path="/">
            {session && session.user ? (
              <Account key={session.user.id} session={session} />
            ) : (
              <Login />
            )}
          </Route>
        </IonRouterOutlet>
      </IonReactRouter>
    </IonApp>
  );
}

// src/App.svelte
<script lang="ts">
  import type { AuthSession } from "@supabase/supabase-js"
  import { onMount } from "svelte"
  import Auth from "./components/Auth/Auth.svelte"
  import ListView from "./components/ListView.svelte"
  import Navbar from "./components/Navbar.svelte"
  import { supabase } from "./lib/supabaseClient"

  let session: AuthSession

  onMount(() => {
    supabase.auth.getSession().then(({ data }) => {
      if (data.session) {
        session = data.session
      }
    })

    supabase.auth.onAuthStateChange((_event, _session) => {
      if (_session) {
        session = _session
      }
    })
  })
</script>

{#if !session}
  <Auth />
{:else}
  <div>
    <!-- <Account {session} /> -->
    <Navbar />
    <ListView />
  </div>
{/if}
